### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by darealshinji** [dubhater/vapoursynth-fieldhint#1]
Since this plugin as well as TemporalSoften, SSIQ and scxvid were ported from original GPL-2 AviSynth plugins (or in case of TemporalSoften from an internal AviSynth function) doesn't that mean those plugins are technically GPL-2 too?

**Comment by dubhater** [comment]
That's fine by me.

**Comment by darealshinji** [comment]
Thanks. What about bifrost? I think the original plugin was closed source.

**Comment by dubhater** [comment]
WTFPL for Bifrost.

**Comment by darealshinji** [comment]
Thanks for the clarification.
